branches:
  only:
    - master

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
      dist: xenial
      language: generic
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: osx
      osx_image: xcode12
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      language: node_js
      node_js:

before_script:
 - chmod +x ./script/*.sh
 - npm install npm -g

script: ./script/travis-build.sh

after_success:
  # Cleanup
  - git reset --hard HEAD
  # Remove untracked and ignored files
  - git clean -dfXn && git clean -dfX
  - chmod +x ./script/*.sh
  # Check if build triggered ([build] in commit message)
  - lgcm=$(git log -1 --pretty=%B | xargs echo);
    if [[ $lgcm == *"[build]"* ]]; then
      ./script/build_ml.sh;
    fi


before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  yarn: true
  apt: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder


notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - xvfb
